# Generated by Django 3.2.3 on 2021-05-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20210527_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='faculty_names',
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='records.faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='records.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_names',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.certificate_type'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.grade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_graduation',
            field=models.IntegerField(default=0),
        ),
    ]
